// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package papyrus.hotel;



/************************************************************/
/**
 * 
 */
public class Client {
	/**
	 * 
	 */
	private String Name;
	/**
	 * 
	 */
	private String DoB;
	/**
	 * 
	 */
	private String Adresse;
	/**
	 * 
	 */
	private String Preferences;
	/**
	 * 
	 */




	public void Reservation() {
		System.out.println("reservation done");
	}
	public Client() {

	}


	public Client(String name, String doB, String adresse, String preferences) {

		Name = name;
		DoB = doB;
		Adresse = adresse;
		Preferences = preferences;
	}

	public String getName() {
		return Name;
	}
	public void setName(String name) {
		Name = name;
	}
	public String getDoB() {
		return DoB;
	}
	public void setDoB(String doB) {
		DoB = doB;
	}
	public String getAdresse() {
		return Adresse;
	}
	public void setAdresse(String adresse) {
		Adresse = adresse;
	}
	public String getPreferences() {
		return Preferences;
	}
	public void setPreferences(String preferences) {
		Preferences = preferences;
	}

}
