// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package papyrus.hotel;

import java.util.Date;

/************************************************************/
/**
 * 
 */
public class MainHotel {
	public static void main(String[] args) {
		Hotel hotel1 = new Hotel();
	    Hotel hotel2 = new Hotel("Delta","6265 5e avenue","Montreal","Canada");
	    hotel1.manage();
	    hotel1.setName("continental");
	    hotel1.getName();
	    hotel2.reservation();
		//hotel.Adresse="adresse";
		Client client1 = new Client();
		Client client2 = new Client("sara", "1994-01-07", "Montreal", "sweetHotel");
		client1.Reservation();
		
		Room room1= new Room();
		Room  room2= new Room(3, 5, 2000);
		room1.CleanRoom();
		
		
		
		Reclamation reclamation= new Reclamation();
		Reclamation reclamation2= new Reclamation(2000, new Date(), "customer service")	;
		reclamation2.Claim();
		
		
		
	}
}
