package papyrus.hotel;

// Code generated by Papyrus Java
// --------------------------------------------------------


/************************************************************/
/**
 * 
 */
public class Room {
	/**
	 * 
	 */
	private int Floor;
	/**
	 * 
	 */
	private int RoomNumber;
	/**
	//public int Qty of beds;
	/**
	 * 
	 */
	private double Price;

	/**
	 * 
	 */
	public void CleanRoom() {
		System.out.println("method CleanRoom is called");

	}

	public Room() {
		System.out.println("constructor of room without parameteres is called");

	}

	public Room(int floor, int roomNumber, double price) {
		Floor = floor;
		 RoomNumber = roomNumber;
		Price = price;
		System.out.printf("constructor of client without parameteres is called, with floor:= %d,RoomNumber:=%d,Price:=%f \n",Floor,RoomNumber,Price);
	}

	public int getFloor() {
		return Floor;
	}

	public void setFloor(int floor) {
		Floor = floor;
	}

	public int getRoomNumber() {
		return RoomNumber;
	}

	public void setRoomNumber(int roomNumber) {
		RoomNumber = roomNumber;
	}

	public double getPrice() {
		return Price;
	}

	public void setPrice(double price) {
		Price = price;
	}


}
