// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package papyrus.hotel;

/************************************************************/
/**
 * 
 */
public class MainHotel {
	public static void main(String[] args) {
		Hotel hotel = new Hotel("Delta","6265 5e avenue","Montreal","Canada");
		//hotel.Adresse="adresse";
		Client client =new Client();
		
	}
}
