// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package papyrus project.hotel_package;



/************************************************************/
/**
 * 
 */
public class Client {
				/**
				 * 
				 */
				private EString[] name;
				/**
				 * 
				 */
				private EString dob;
				/**
				 * 
				 */
				private EString adresse;
				/**
				 * 
				 */
				private EString preferences;
				/**
				 * 
				 */
				public Reclamation[] reclamation;
				/**
				 * 
				 */
				public Room[] room;
	/**
	 * 
	 */
	public void reservation() {
	}
	/**
	 * 
	 */
	public void Client() {
	}
	/**
	 * 
	 * @param name 
	 * @param dob 
	 * @param adresse 
	 * @param prefernces 
	 */
	public void Client(EString name, EString dob, EString adresse, EString prefernces) {
	}
}
