// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package papyrus project.hotel_package;



/************************************************************/
/**
 * 
 */
public class Hotel {
				/**
				 * 
				 */
				private EString name;
				/**
				 * 
				 */
				private EString adresse;
				/**
				 * 
				 */
				private EString country;
				/**
				 * 
				 */
				public EString city;
				/**
				 * 
				 */
				public Hotel hotel;
				/**
				 * 
				 */
				public Room[] room;
	/**
	 * 
	 */
	public void reservation() {
	}
	/**
	 * 
	 */
	public void manage() {
	}
	/**
	 * 
	 */
	public void Hotel() {
	}
	/**
	 * 
	 * @param name 
	 * @param adresse 
	 * @param city 
	 * @param country 
	 */
	public void Hotel(EString name, EString adresse, EString city, EString country) {
	}
}
