// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package papyrus

project.hotel_package;

import papyrus project.int;

/************************************************************/
/**
 * 
 */
public class Reclamation {
	/**
	 * 
	 */
	private int claimNumber;
	/**
	 * 
	 */
	private EDate date;
	/**
	 * 
	 */
	private EString raison;

	/**
	 * 
	 */
	public void claim() {
	}

	/**
	 * 
	 */
	public void Reclamation() {
	}

	/**
	 * 
	 * @param claimNumber 
	 * @param date 
	 * @param raison 
	 */
	public void Reclamation(EInt claimNumber, EDate date, EString raison) {
	}
}
