// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package papyrus

project.hotel_package;

import papyrus project.int;

/************************************************************/
/**
 * 
 */
public class Room {
	/**
	 * 
	 */
	private EInt floor;
	/**
	 * 
	 */
	private EInt roomNumber;
	/**
	 * 
	 */
	private int qtyOfbeds;
	/**
	 * 
	 */
	private EDouble price;

	/**
	 * 
	 */
	public void cleanRoom() {
	}

	/**
	 * 
	 */
	public void Room() {
	}

	/**
	 * 
	 * @param floor 
	 * @param roomNumber 
	 * @param qtyOfBed 
	 * @param price 
	 */
	public void Room(EInt floor, EInt roomNumber, EInt qtyOfBed, EDouble price) {
	}
}
