// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package papyrus.hotel;



/************************************************************/
/**
 * 
 */
public class Client {
				/**
				 * 
				 */
				public String[] Name;
				/**
				 * 
				 */
				public String DoB;
				/**
				 * 
				 */
				public String Adresse;
				/**
				 * 
				 */
				public String Preferences;
				/**
				 * 
				 */
				
	
	public void Reservation() {
		System.out.println("reservation done");
	}
}
